settings:
  title: 'Monitoramento sites da OKAD'
  url: 'https://status-page.okad.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos os sites estão online'
  notAllmonitorsOperational: 'Alguns sites estão offline'
  monitorLabelOperational: 'Online'
  monitorLabelNotOperational: 'Offline'
  monitorLabelNoData: 'Sem dados'
  dayInHistogramNoData: 'Sem dados'
  dayInHistogramOperational: 'Tudo ok'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: okad-homepage # unique identifier
    name: www.okad.com.br
    description: 'Página inicial da OKAD' # default=empty
    url: 'https://www.okad.com.br/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
